export type {
  ApiResponse,
  ApiError,
  ProductQueryParams,
} from "./types";
export {
  apiClient,
  fetchWithAuth,
  buildProductQuery,
} from "./client";
export {
  getProducts,
  getProduct,
  getProductReviews,
  createReview,
  deleteReview,
  getCategories,
  getTags,
  getCart,
  addToCart,
  updateCartItem,
  removeCartItem,
  clearCart,
  createOrder,
  getOrders,
  getOrder,
  getMe,
} from "./customer";
export {
  getDashboard,
  getAnalytics,
  getInventory,
  getAdminProducts,
  getAdminProduct,
  createProduct,
  updateProduct,
  updateProductInventory,
  deleteProduct,
  getAdminCategories,
  createCategory,
  updateCategory,
  deleteCategory,
  getAdminTags,
  createTag,
  updateTag,
  deleteTag,
  getUsers,
  getUser,
  updateUser,
  deleteUser,
  getAdminOrders,
  getAdminOrder,
  updateOrderStatus,
  getNotificationEmails,
  createNotificationEmail,
  updateNotificationEmail,
  deleteNotificationEmail,
} from "./admin";
export type {
  ProductBrief,
  ProductDetail,
  ProductCreateInput,
  ProductUpdateInput,
  Category,
  Tag,
  CategoryInput,
  TagInput,
  Cart,
  CartItem,
  Order,
  Review,
  User,
  CheckoutData,
  ReviewInput,
  AddToCartInput,
  UpdateCartInput,
} from "./customer";